-- PostgreSQL schema for Neon/Supabase
-- Run this in the SQL editor before deploying the backend.

DROP VIEW IF EXISTS vw_user_admin_summary CASCADE;
DROP VIEW IF EXISTS vw_leaderboard CASCADE;

DROP TABLE IF EXISTS leaderboard_snapshots CASCADE;
DROP TABLE IF EXISTS predictions CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS stages CASCADE;
DROP TABLE IF EXISTS tournament_participants CASCADE;
DROP TABLE IF EXISTS tournaments CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    member_code VARCHAR(20) NULL,
    full_name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NULL,
    google_id VARCHAR(255) NULL,
    avatar_url VARCHAR(500) NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'PLAYER',
    user_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'PLAYER')),
    CONSTRAINT chk_users_status CHECK (user_status IN ('ACTIVE', 'INACTIVE', 'PENDING'))
);

CREATE TABLE tournaments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    sport_type VARCHAR(50) NOT NULL DEFAULT 'FOOTBALL',
    format VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'UPCOMING',
    visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    created_by INTEGER NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_tournaments_sport_type CHECK (sport_type IN ('FOOTBALL', 'BASKETBALL', 'ESPORTS')),
    CONSTRAINT chk_tournaments_format CHECK (format IN ('GROUP_AND_KNOCKOUT', 'ROUND_ROBIN', 'KNOCKOUT')),
    CONSTRAINT chk_tournaments_status CHECK (status IN ('UPCOMING', 'ACTIVE', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_tournaments_visibility CHECK (visibility IN ('PUBLIC', 'PRIVATE'))
);

CREATE TABLE tournament_participants (
    tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (tournament_id, user_id)
);

CREATE TABLE stages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL,
    correct_points INTEGER NOT NULL DEFAULT 1,
    exact_score_bonus INTEGER NOT NULL DEFAULT 0,
    is_knockout BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (tournament_id, sort_order),
    CONSTRAINT chk_stages_points CHECK (correct_points >= 0 AND exact_score_bonus >= 0)
);

CREATE TABLE teams (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    group_name VARCHAR(20) NULL,
    logo_url VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (tournament_id, name)
);

CREATE TABLE matches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
    stage_id INTEGER NOT NULL REFERENCES stages(id) ON DELETE CASCADE,
    home_team_id INTEGER NULL REFERENCES teams(id),
    away_team_id INTEGER NULL REFERENCES teams(id),
    home_placeholder VARCHAR(100) NULL,
    away_placeholder VARCHAR(100) NULL,
    scheduled_time TIMESTAMPTZ NOT NULL,
    lock_minutes_before_start INTEGER NOT NULL DEFAULT 15,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    actual_home_score INTEGER NULL,
    actual_away_score INTEGER NULL,
    winner_team_id INTEGER NULL REFERENCES teams(id),
    external_source VARCHAR(50) NULL,
    external_match_id VARCHAR(100) NULL,
    last_synced_at TIMESTAMPTZ NULL,
    sync_status VARCHAR(30) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_matches_status CHECK (status IN ('PENDING', 'LIVE', 'FINISHED', 'CANCELLED')),
    CONSTRAINT chk_matches_scores CHECK ((actual_home_score IS NULL OR actual_home_score >= 0) AND (actual_away_score IS NULL OR actual_away_score >= 0)),
    CONSTRAINT chk_matches_lock_minutes CHECK (lock_minutes_before_start >= 0)
);

CREATE TABLE predictions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    predicted_outcome VARCHAR(20) NOT NULL,
    predicted_home_score INTEGER NULL,
    predicted_away_score INTEGER NULL,
    points_earned INTEGER NOT NULL DEFAULT 0,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, match_id),
    CONSTRAINT chk_predictions_outcome CHECK (predicted_outcome IN ('HOME_WIN', 'DRAW', 'AWAY_WIN')),
    CONSTRAINT chk_predictions_scores CHECK ((predicted_home_score IS NULL OR predicted_home_score >= 0) AND (predicted_away_score IS NULL OR predicted_away_score >= 0)),
    CONSTRAINT chk_predictions_points CHECK (points_earned >= 0)
);

CREATE TABLE leaderboard_snapshots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    snapshot_date DATE NOT NULL,
    cumulative_points INTEGER NOT NULL DEFAULT 0,
    daily_points INTEGER NOT NULL DEFAULT 0,
    rank_no INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (tournament_id, user_id, snapshot_date),
    CONSTRAINT chk_ls_points CHECK (cumulative_points >= 0 AND daily_points >= 0),
    CONSTRAINT chk_ls_rank CHECK (rank_no > 0)
);

CREATE INDEX idx_users_email ON users(email);
CREATE UNIQUE INDEX uq_users_member_code ON users(member_code) WHERE member_code IS NOT NULL;
CREATE INDEX idx_tournaments_status ON tournaments(status);
CREATE INDEX idx_tournament_participants_user ON tournament_participants(user_id);
CREATE INDEX idx_stages_tournament ON stages(tournament_id);
CREATE INDEX idx_teams_tournament_group ON teams(tournament_id, group_name);
CREATE INDEX idx_matches_tournament_time ON matches(tournament_id, scheduled_time);
CREATE INDEX idx_matches_tournament_status ON matches(tournament_id, status);
CREATE INDEX idx_matches_external ON matches(external_source, external_match_id);
CREATE INDEX idx_predictions_match ON predictions(match_id);
CREATE INDEX idx_predictions_user ON predictions(user_id);
CREATE INDEX idx_leaderboard_snapshots_tournament_date_rank ON leaderboard_snapshots(tournament_id, snapshot_date, rank_no);

CREATE VIEW vw_user_admin_summary AS
SELECT
    u.id,
    u.member_code,
    u.email,
    u.full_name,
    u.role,
    u.user_status,
    u.created_at,
    u.updated_at,
    COUNT(DISTINCT tp.tournament_id) AS events_count
FROM users u
LEFT JOIN tournament_participants tp ON tp.user_id = u.id
GROUP BY u.id, u.member_code, u.email, u.full_name, u.role, u.user_status, u.created_at, u.updated_at;

CREATE VIEW vw_leaderboard AS
SELECT
    t.id AS tournament_id,
    u.id AS user_id,
    u.full_name,
    u.email,
    SUM(p.points_earned) AS total_points,
    COUNT(p.id) AS total_predictions,
    SUM(CASE WHEN p.points_earned > 0 THEN 1 ELSE 0 END) AS correct_predictions
FROM users u
JOIN predictions p ON p.user_id = u.id
JOIN matches m ON m.id = p.match_id
JOIN tournaments t ON t.id = m.tournament_id
GROUP BY t.id, u.id, u.full_name, u.email;
